name: Pandoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: mkdir
      run: |
       mkdir public
       
    - name: Generate PDF with Pandoc
      uses: docker://pandoc/latex:2.9
      with:
        args: "-t revealjs -s -o index.html index.md -V revealjs-url=https://unpkg.com/reveal.js@3.9.2/"

    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: paper
        path: .
